services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=twitter
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    env_file:
      - application.env
    networks:
      - twitter_net

  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: twitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: psql -U postgres twitter
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - twitter_net
    restart: always

volumes:
  postgres_data:

networks:
  twitter_net:
