services:
  postgres-main:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: twitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres-test:
    image: postgres:12
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: twittertest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
